name: Timeout Example

on: [push]
concurrency:
  group: ${{ github.repository }}-${{ github.ref }}
  #cancel-in-progress: false 
  cancel-in-progress: true # it will cancel the running one, pickup new one
jobs:
  timeout-job:
    runs-on: ubuntu-latest
    # Set job-level timeout to 5 minutes
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print message
        run: echo "This job will timeout after 5 minutes if it runs too long."

      - name: Simulate long task
        run: |
          echo "Starting a long task..."
          sleep 600   # 600 seconds = 10 minutes
          echo "Finished!"
