name: conditions

on: [push] 

jobs: 
  conditions-demo: 
    runs-on: ubuntu-latest 
    steps:
      - name: Say hello
        run: echo "Hello, world!"
      - name: trigger the PROD
        if: github.ref == 'refs/heads/main'
        run: echo 'Deploying the prod'
      - name: trigger the DEV
        if: github.ref == 'refs/heads/feature-*'
        run: echo 'Deploying the dev'